# Generated by Django 5.0.1 on 2026-02-08 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('publications', models.JSONField(blank=True, default=list, help_text='List of publication names')),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('truthfulness_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of validated claims that were true', max_digits=5)),
                ('speed_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of original scoops that were first to report', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journalist',
                'verbose_name_plural': 'Journalists',
                'ordering': ['-truthfulness_score', '-speed_score'],
                'indexes': [models.Index(fields=['-truthfulness_score'], name='claims_jour_truthfu_554d8c_idx'), models.Index(fields=['-speed_score'], name='claims_jour_speed_s_b2bd03_idx'), models.Index(fields=['name'], name='claims_jour_name_682ca2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField(help_text='The actual claim made')),
                ('publication', models.CharField(max_length=200)),
                ('article_url', models.URLField()),
                ('claim_date', models.DateTimeField(db_index=True)),
                ('player_name', models.CharField(blank=True, max_length=200)),
                ('from_club', models.CharField(blank=True, max_length=200)),
                ('to_club', models.CharField(blank=True, max_length=200)),
                ('transfer_fee', models.CharField(blank=True, help_text="e.g., '50M', 'Free transfer'", max_length=100)),
                ('certainty_level', models.CharField(choices=[('confirmed', 'Confirmed'), ('sources_say', 'Sources Say'), ('rumoured', 'Rumoured'), ('speculation', 'Speculation')], default='rumoured', max_length=20)),
                ('source_type', models.CharField(choices=[('original', 'Original Scoop'), ('citing', 'Citing Another Source')], default='original', max_length=20)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Validation'), ('confirmed_true', 'Confirmed True'), ('proven_false', 'Proven False'), ('partially_true', 'Partially True')], db_index=True, default='pending', max_length=20)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('validation_notes', models.TextField(blank=True, help_text='Admin notes on validation')),
                ('validation_source_url', models.URLField(blank=True, help_text='URL proving true/false')),
                ('is_first_claim', models.BooleanField(db_index=True, default=False, help_text='Was this journalist first to report this story?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cited_journalist', models.ForeignKey(blank=True, help_text='If this claim cites another journalist, reference them here', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cited_claims', to='claims.journalist')),
                ('journalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claims.journalist')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truthfulness_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('speed_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_claims', models.IntegerField()),
                ('validated_claims', models.IntegerField()),
                ('true_claims', models.IntegerField()),
                ('false_claims', models.IntegerField()),
                ('original_scoops', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('journalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='claims.journalist')),
            ],
            options={
                'verbose_name': 'Score History',
                'verbose_name_plural': 'Score Histories',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('from_club', models.CharField(max_length=200)),
                ('to_club', models.CharField(max_length=200)),
                ('transfer_window', models.CharField(help_text="e.g., 'Summer 2026', 'Winter 2026'", max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('actual_fee', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_for_transfer', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['-claim_date'], name='claims_clai_claim_d_bf2f08_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['validation_status', '-claim_date'], name='claims_clai_validat_38e289_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['player_name'], name='claims_clai_player__289122_idx'),
        ),
        migrations.AddIndex(
            model_name='scorehistory',
            index=models.Index(fields=['journalist', '-recorded_at'], name='claims_scor_journal_09c521_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transfer',
            unique_together={('player_name', 'to_club', 'transfer_window')},
        ),
    ]
