# Generated by Django 5.0.1 on 2026-02-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, unique=True)),
                ('source_type', models.CharField(choices=[('rss', 'RSS Feed'), ('twitter', 'Twitter'), ('web', 'Web Scrape')], max_length=20)),
                ('source_name', models.CharField(help_text="e.g. 'BBC Sport RSS'", max_length=200)),
                ('raw_content', models.TextField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('claims_created', models.IntegerField(default=0)),
                ('processing_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Scraped Article',
                'verbose_name_plural': 'Scraped Articles',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['-scraped_at'], name='claims_scra_scraped_f43592_idx'), models.Index(fields=['processed'], name='claims_scra_process_b90b5e_idx')],
            },
        ),
    ]
