# Generated by Django 5.0.1 on 2026-02-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claim_certainty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedarticle',
            name='source_type',
            field=models.CharField(choices=[('rss', 'RSS Feed'), ('twitter', 'Twitter'), ('web', 'Web Scrape'), ('reddit', 'Reddit')], max_length=20),
        ),
    ]
