# Generated by Django 5.0.1 on 2026-02-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_add_reddit_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='article_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='claim',
            name='from_club',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='claim',
            name='player_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='claim',
            name='publication',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='claim',
            name='to_club',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='claim',
            name='validation_source_url',
            field=models.URLField(blank=True, help_text='URL proving true/false', max_length=1000),
        ),
    ]
